// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ui} from '../models';
import {sync} from '../models';

export function CompleteReviewSession(arg1:main.ReviewSessionSummaryInput):Promise<string>;

export function GetDashboardSnapshot():Promise<ui.DashboardSnapshot>;

export function GetNextDueCard():Promise<main.ReviewCardDTO>;

export function GetStartupStatus():Promise<string>;

export function GetSyncSettings():Promise<main.SyncSettingsDTO>;

export function GetSyncStatus():Promise<sync.SyncStatus>;

export function IngestDocument(arg1:string,arg2:string):Promise<string>;

export function JoinClass(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.JoinClassResponse>;

export function PickDocumentPath():Promise<string>;

export function ProbeCloudHealth(arg1:string):Promise<main.CloudHealthProbeResult>;

export function RateDueCard(arg1:main.ReviewRateInput):Promise<main.ReviewRateResult>;

export function RunManualSync():Promise<string>;

export function SaveSyncSettings(arg1:string,arg2:string):Promise<string>;

export function StreamRAGAnswer(arg1:string):Promise<string>;
