// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteReviewSession(arg1) {
  return window['go']['main']['App']['CompleteReviewSession'](arg1);
}

export function GetDashboardSnapshot() {
  return window['go']['main']['App']['GetDashboardSnapshot']();
}

export function GetNextDueCard() {
  return window['go']['main']['App']['GetNextDueCard']();
}

export function GetStartupStatus() {
  return window['go']['main']['App']['GetStartupStatus']();
}

export function GetSyncSettings() {
  return window['go']['main']['App']['GetSyncSettings']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function IngestDocument(arg1, arg2) {
  return window['go']['main']['App']['IngestDocument'](arg1, arg2);
}

export function PickDocumentPath() {
  return window['go']['main']['App']['PickDocumentPath']();
}

export function ProbeCloudHealth(arg1) {
  return window['go']['main']['App']['ProbeCloudHealth'](arg1);
}

export function RateDueCard(arg1) {
  return window['go']['main']['App']['RateDueCard'](arg1);
}

export function RunManualSync() {
  return window['go']['main']['App']['RunManualSync']();
}

export function SaveSyncSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSyncSettings'](arg1, arg2);
}

export function StreamRAGAnswer(arg1) {
  return window['go']['main']['App']['StreamRAGAnswer'](arg1);
}
