// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboardSnapshot() {
  return window['go']['main']['App']['GetDashboardSnapshot']();
}

export function GetStartupStatus() {
  return window['go']['main']['App']['GetStartupStatus']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function RunManualSync() {
  return window['go']['main']['App']['RunManualSync']();
}
