// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';

export function GetDashboardSnapshot():Promise<ui.DashboardSnapshot>;

export function GetStartupStatus():Promise<string>;
