// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';
import {sync} from '../models';

export function GetDashboardSnapshot():Promise<ui.DashboardSnapshot>;

export function GetStartupStatus():Promise<string>;

export function GetSyncStatus():Promise<sync.SyncStatus>;

export function RunManualSync():Promise<string>;
